Repository umijs/umi-ui, pull requests merged in 2020-04, with the labels that each got.

#46 🐛 bug：fix copy file no find error in windows
  packages/block-sdk/package.json
  packages/block-sdk/src/addBlock.ts
  packages/block-sdk/src/appendBlockToContainer.ts
  packages/block-sdk/src/getBlockGenerator.ts
  packages/block-sdk/src/util.ts
  yarn.lock
Labels: bug

#47 fix: config detect and insertComponent bug
  packages/block-sdk/src/appendBlockToContainer.ts
  packages/block-sdk/src/sdk/util.ts
  packages/plugin-ui-blocks/src/ui/server/socketHandlers/index.test.ts
  packages/plugin-ui-blocks/src/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
Labels: bug

#48 fix: pro table insert bug
  packages/plugin-ui-blocks/src/sdk/flagBabelPlugin/fixtures/pro-table/expected.js
  packages/plugin-ui-blocks/src/sdk/flagBabelPlugin/fixtures/pro-table/origin.tsx
  packages/plugin-ui-blocks/src/sdk/flagBabelPlugin/index.ts
  packages/plugin-ui-blocks/src/sdk/util.ts
  packages/plugin-ui-blocks/ui/BlockList/getInsertPosition.tsx
Labels: bug

#52 fix: block view and port display
  azure-pipelines.yml
  packages/plugin-ui-blocks/src/sdk/flagBabelPlugin/index.ts
  packages/plugin-ui-blocks/src/ui/server/util/index.ts
  packages/plugin-ui-blocks/ui/BlockList/index.tsx
  packages/plugin-ui-blocks/ui/BlocksViewer.tsx
  packages/ui/src/UmiUI.ts
Labels: bug

#55 feat: support <UmiUIFlag />
  README.md
  package.json
  packages/preset-ui/src/UmiUIFlag.ts
  packages/preset-ui/src/index.ts
  packages/preset-ui/src/templates/UmiUIFlag.tpl
Labels: enhancement

#56 🏗 scrtipt: default select master branch
  packages/block-sdk/src/download.test.ts
  packages/block-sdk/src/download.ts
  packages/plugin-ui-blocks/src/sdk/flagBabelPlugin/index.test.ts
Labels: dependency

#57 fix: windows project name
  packages/ui/src/Config.ts
  yarn.lock
Labels: bug

#60 fix: theme ui build
  packages/ui-builder/index.js
  packages/ui-builder/package.json
Labels: bug

#62 fix: clear module
  packages/ui/src/UmiUI.ts
Labels: bug

#63 chore: intl
  packages/plugin-ui-blocks/ui/Adder/AddBlockFormForUI.tsx
  packages/plugin-ui-blocks/ui/locales/en-US.js
  packages/plugin-ui-blocks/ui/locales/zh-CN.js
Labels: chore

#64 feat(plugin-ui-blocks): support the dynamic appended function component
  packages/plugin-ui-blocks/src/ui/index.ts
Labels: bug

#66 fix: route component with string function
  packages/plugin-ui-blocks/src/ui/index.ts
Labels: bug
